name: greendayo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.0.0<4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_web_plugins:
    sdk: flutter
  hooks_riverpod: ^3.0.3
  flutter_hooks:
  riverpod_annotation: ^3.0.3
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_messaging: ^16.1.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.5.3
  json_serializable: ^6.9.5
  rxdart: ^0.28.0
  dartz: ^0.10.1
  video_player: ^2.9.5
  video_player_web: ^2.3.4
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  sign_in_button: ^4.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^2.0.1
  socket_io_client: ^3.1.1
  http: ^1.3.0
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  image: ^4.5.4
  ulid: ^2.0.1
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  flutter_shaders: ^0.1.3
  web: any
  flutter_riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/models/
    - assets/images/
    - assets/videos/

  shaders:
    - shaders/flip.frag
    - shaders/dots.frag
    - shaders/spiral.frag

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: '#3E2723'
  image: 'assets/images/splash.png'
